# Generated by Django 4.0.2 on 2022-04-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
