# Generated by Django 4.0.2 on 2022-04-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_alter_comment_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='img/%y'),
        ),
    ]
